export const LOGIN ='LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';


export const FETCH_DATA ='FETCH_DATA';
export const FETCH_DATA_SUCCESS ='FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR ='FETCH_DATA_ERROR';

export const ADD_USER_POSTS="ADD_USER_POSTS";

export const UPLOAD_IMAGE='UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS='UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR='UPLOAD_IMAGE_ERROR';

export const ADD_USER ='ADD_USER'

export const LOGOUT ='LOGOUT';
